module a_o_b32(
	a,
	b,
	add_or_sub,
	cin,
	res,
	cout);

	//---Ports declearation: generated by Robei---
	input [31:0] a;
	input [31:0] b;
	input add_or_sub;
	input cin;
	output [31:0] res;
	output cout;

	wire [31:0] a;
	wire [31:0] b;
	wire add_or_sub;
	wire cin;
	wire [31:0] res;
	wire cout;

	//----Code starts here: integrated by Robei-----
	    assign {cout, res} = add_or_sub ? (a + ~b) + (~cin) : (a + b + cin);
endmodule    //a_o_b32

