module control(
	alu_op,
	reg_write,
	alu_src,
	mem_read,
	mem_write,
	branch,
	jump,
	mem_to_reg,
	inst);

	//---Ports declearation: generated by Robei---
	output [3:0] alu_op;
	output reg_write;
	output alu_src;
	output mem_read;
	output mem_write;
	output branch;
	output jump;
	output mem_to_reg;
	input [31:0] inst;

	wire [3:0] alu_op;
	wire reg_write;
	wire alu_src;
	wire mem_read;
	wire mem_write;
	wire branch;
	wire jump;
	wire mem_to_reg;
	wire [31:0] inst;

	//----Code starts here: integrated by Robei-----
	wire [6:0] opcode = inst[6:0];
	wire [2:0] funct3 = inst[14:12];
	wire [6:0] funct7 = inst[31:25];
	 // ��ȡָ���ֶ�
	    wire is_r_type = (opcode == 7'b0110011);
	    wire is_i_type = (opcode == 7'b0010011) || (opcode == 7'b0000011);
	    wire is_s_type = (opcode == 7'b0100011);
	    wire is_b_type = (opcode == 7'b1100011);
	    wire is_u_type = (opcode == 7'b0110111) || (opcode == 7'b0010111);
	    wire is_j_type = (opcode == 7'b1101111);
	
	    // ALU������
	    assign alu_op =
	        (is_r_type && funct3 == 3'b000 && funct7 == 7'b0000000) ? 4'b0000 : // add
	        (is_r_type && funct3 == 3'b000 && funct7 == 7'b0100000) ? 4'b0001 : // sub
	        (is_r_type && funct3 == 3'b111) ? 4'b0010 :                         // and
	        (is_r_type && funct3 == 3'b110) ? 4'b0011 :                         // or
	        (is_i_type && funct3 == 3'b000) ? 4'b0000 :                         // addi
	        (is_i_type && funct3 == 3'b010) ? 4'b0000 :                         // lw (addr add)
	        (is_s_type)                     ? 4'b0000 :                         // sw (addr add)
	        (is_b_type)                     ? 4'b0001 :                         // beq (sub)
	        4'b0000;
	
	    // �����ź�
	    assign reg_write  = is_r_type || is_i_type || is_u_type || is_j_type || (opcode == 7'b0110111);
	    assign alu_src    = is_i_type || is_s_type || is_u_type;
	    assign mem_read   = (opcode == 7'b0000011);
	    assign mem_write  = is_s_type;
	    assign branch     = is_b_type;
	    assign jump       = is_j_type;
	    assign mem_to_reg = (opcode == 7'b0000011);
endmodule    //control

