module imm_gen(
	p0,
	p1);

	//---Ports declearation: generated by Robei---
	input [31:0] p0;
	output [31:0] p1;

	wire [31:0] p0;
	wire [31:0] p1;

	//----Code starts here: integrated by Robei-----
	    wire [6:0] opcode = p0[6:0];
	
	    assign p1 = 
	        // I-type: lw, addi, jalr, csr
	        (opcode == 7'b0000011 || opcode == 7'b0010011 || opcode == 7'b1100111) ?
	            {{21{p0[31]}}, p0[30:20]} :
	        // S-type: sw
	        (opcode == 7'b0100011) ?
	            {{21{p0[31]}}, p0[30:25], p0[11:7]} :
	        // B-type: beq, bne, blt, bge
	        (opcode == 7'b1100011) ?
	            {{20{p0[31]}}, p0[7], p0[30:25], p0[11:8], 1'b0} :
	        // U-type: lui, auipc
	        (opcode == 7'b0110111 || opcode == 7'b0010111) ?
	            {p0[31:12], 12'b0} :
	        // J-type: jal
	        (opcode == 7'b1101111) ?
	            {{12{p0[31]}}, p0[19:12], p0[20], p0[30:21], 1'b0} :
	        32'b0;  // Ĭ�����0
endmodule    //imm_gen

