module mux32(
	a,
	b,
	en,
	out);

	//---Ports declearation: generated by Robei---
	input [31:0] a;
	input [31:0] b;
	input en;
	output [31:0] out;

	wire [31:0] a;
	wire [31:0] b;
	wire en;
	wire [31:0] out;

	//----Code starts here: integrated by Robei-----
	    assign out = en ? b : a;
endmodule    //mux32

