module pc(
	clk,
	rst_n,
	jump_valid,
	jump_addr,
	pc_addr);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input jump_valid;
	input [31:0] jump_addr;
	output [31:0] pc_addr;

	wire clk;
	wire rst_n;
	wire jump_valid;
	wire [31:0] jump_addr;
	wire [31:0] pc_addr;
	wire [31:0] a_o_b322_res;
	wire [31:0] mux323_out;
	wire [31:0] reg323_p3;
	assign pc_addr = reg323_p3;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	a_o_b32 a_o_b322(
    .a(reg323_p3),
    .b(32'd4),
    .add_or_sub(1'b0),   // 明确写1位
    .cin(1'b0),          // 明确写1位
    .res(a_o_b322_res)
	);

	mux32 mux323(
		.a(a_o_b322_res),
		.b(jump_addr),
		.en(jump_valid),
		.out(mux323_out));

	reg32 reg323(
		.clk(clk),
		.rst_n(rst_n),
		.D(mux323_out),
		.Q(reg323_p3));

endmodule    //pc

