name: gds

on: [push]

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tiny Tapeout GDS action
        uses: TinyTapeout/tt-gds-action@main
