name: gds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build submission
        uses: TinyTapeout/tt-gds-action@v3
        with:
          input_dir: .
